### ISSUE TITLE
dedicated cache database not created with steps from readme

### ISSUE THREAD

**Issue by vokshirg** [rails/solid_cache#150]
When I follow steps from [here](https://github.com/rails/solid_cache?tab=readme-ov-file#using-a-dedicated-cache-database)  to create dedicated cache database, I run command `rails db:create` but get only response that my dev database already exists. And `cache_development` has not been created

```yml
# database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: my_app_development
  cache:
    database: cache_development
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: "db/cache/migrate"
```

what am i missing? I'm using postgresql, does it supported with this syntax?

**Comment by vokshirg** [comment]
oh, my bad, that works 🙈

```yml
development:
  primary:
    <<: *default
    database: my_app_development
  cache:
    database: cache_development
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: "db/cache/migrate"
```
