### ISSUE TITLE
NoMethodError: undefined method `read' for class SolidCache::Entry

### ISSUE THREAD

**Issue by amkisko** [rails/solid_cache#237]
Hey!

After full setup, getting this error:
```
$ bin/rails c

> Rails.cache.exist?("test")
NoMethodError: undefined method `read' for class SolidCache::Entry
from /Users/me/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
```

Can't figure out what's missing, anybody got the same?

Setup:
- cache.yml
```yaml
default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```
- config/environments/development.rb
```ruby
config.cache_store = :solid_cache_store
```

- Gemfile.lock
```ruby
    rails (7.2.1.2)
      actioncable (= 7.2.1.2)
      actionmailbox (= 7.2.1.2)
      actionmailer (= 7.2.1.2)
      actionpack (= 7.2.1.2)
      actiontext (= 7.2.1.2)
      actionview (= 7.2.1.2)
      activejob (= 7.2.1.2)
      activemodel (= 7.2.1.2)
      activerecord (= 7.2.1.2)
      activestorage (= 7.2.1.2)
      activesupport (= 7.2.1.2)
      bundler (>= 1.15.0)
      railties (= 7.2.1.2)
    solid_cache (1.0.6)
      activejob (>= 7.2)
      activerecord (>= 7.2)
      railties (>= 7.2)

RUBY VERSION
   ruby 3.3.4p94

BUNDLED WITH
   2.5.20
```
