### ISSUE TITLE
PG::UndefinedTable: ERROR: relation "solid_cache_entries" does not exist

### ISSUE THREAD

**Issue by SylarRuby** [rails/solid_cache#264]
Rails 8 using postgresql. When tried to log in, I get the error:

> PG::UndefinedTable: ERROR: relation "solid_cache_entries" does not exist LINE 10: WHERE a.attrelid = '"solid_cache_entries"'::regclass ^

config/cable.yml:
```yml
development:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
```

With some trial and error, in SessionsController, I commented out this line and it worked:

```rb
rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }
```

I've always used mysql without any issues. Once that line is commented out, I could sign in and everything works, but could not when line 3 is present.
